Regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# From configure.in Revision: 1.8 
+# From configure.in Revision: 1.9 
 
 
 
@@ -1958,14 +1958,60 @@ echo "configure:1955: checking for $pseexe" >&5
 	    fi
 	    ;;
     esac
+saveCPPFLAGS=$CPPFLAGS
+CPPFLAGS="$CPPFLAGS $V_INCLS"
+ac_safe=`echo "pcap-int.h" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for pcap-int.h""... $ac_c" 1>&6
+echo "configure:1966: checking for pcap-int.h" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1971 "configure"
+#include "confdefs.h"
+#include <pcap-int.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1976: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  :
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+CPPFLAGS=$saveCPPFLAGS
+if test "$ac_cv_header_pcap_int_h" = "yes"
+then
+	cat >> confdefs.h <<\EOF
+#define HAVE_PCAP_INT_H 1
+EOF
+
+else
+	echo "configure: warning: No pcap-int.h; tcpslice may not be able to read dump files." 1>&2
+	echo "configure: warning: Try building with a local copy of the libpcap source." 1>&2
+fi
 
 echo $ac_n "checking for int32_t using $CC""... $ac_c" 1>&6
-echo "configure:1964: checking for int32_t using $CC" >&5
+echo "configure:2010: checking for int32_t using $CC" >&5
     if eval "test \"`echo '$''{'ac_cv_lbl_have_int32_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1969 "configure"
+#line 2015 "configure"
 #include "confdefs.h"
 
 #	include "confdefs.h"
@@ -1978,7 +2024,7 @@ int main() {
 int32_t i
 ; return 0; }
 EOF
-if { (eval echo configure:1982: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2028: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_lbl_have_int32_t=yes
 else
@@ -1998,12 +2044,12 @@ EOF
 
     fi
 echo $ac_n "checking for u_int32_t using $CC""... $ac_c" 1>&6
-echo "configure:2002: checking for u_int32_t using $CC" >&5
+echo "configure:2048: checking for u_int32_t using $CC" >&5
     if eval "test \"`echo '$''{'ac_cv_lbl_have_u_int32_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2007 "configure"
+#line 2053 "configure"
 #include "confdefs.h"
 
 #	include "confdefs.h"
@@ -2016,7 +2062,7 @@ int main() {
 u_int32_t i
 ; return 0; }
 EOF
-if { (eval echo configure:2020: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2066: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_lbl_have_u_int32_t=yes
 else
@@ -2102,7 +2148,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:2106: checking for a BSD compatible install" >&5
+echo "configure:2152: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
